name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # To create releases and push tags
      issues: write # To create release issues
      pull-requests: write # To create release pull requests
      id-token: write # For OIDC authentication with npm

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for semantic-release to analyze all commits

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Used by @semantic-release/github
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Used by @semantic-release/npm
        run: npx semantic-release